name: deploy to ec2
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh로 ec2 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/2024testback
            git pull origin main
            ./gradlew bootwar
            sudo fuser -k -n tcp 8080 || true
            sudo nohup java -jar build/libs/*SNAPSHOT.war > ./output.log 2>&1 &
